### ISSUE TITLE
Latest update appears to break eval

### ISSUE THREAD

**Issue by afxefx** [SirGoodenough/Availability-Template#2]
The latest update appears to have broken something.  Using my previous avail template, pulled from example here but with my entities, it is always evaluating to False currently.  I rolled back to previous version and the issue no longer exists.  No errors in log to post but I placed the following in template dev and it always eval'd to False regardless of what entity I supplied although all supplied entities were available:

```
{% from 'availability_template.jinja' import avail %}
{{- avail(['sensor.pirateweather_daytime_high_temperature_0d','sensor.wupws_temp_high_2d']) | bool -}}
```

**Comment by SirGoodenough** [comment]
In the last version I pushed up, I added undefined & null as a false and forced the value to lower case.  
Do any of your entities have these values?
If you look at those entities in developer - state you can see the state.

from:
```jinja
{{- entity_list | map('states') | reject('in', ['unknown','unavailable','','none'])
```
to
```jinja
{{- entity_list | map('states') | lower | reject('in', ["undefined", "unknown", "unavailable", "none", "null", ""])
```

Obviously I can't test everything, but I have replaced all the opportunities I have in my system with this template to test it and this change didn't pick up any false flags in my config. That not saying this code is not causing problems, it could be.

**Comment by afxefx** [comment]
No worries and I appreciate the response.  I have verified that those entities listed above have a valid value.  Even tested a few others just to make sure.  Rolling back to the previous version immediately resolves it but if I upgrade the two binary sensors I have set up become unavailable.  Posting binary yaml below for reference and devtools for the two sensors I'm using:

![image](https://github.com/SirGoodenough/Availability-Template/assets/3475494/8b450a20-fe51-4afa-aa34-18ca527ddb35)

```
windows_should_be_open:
        friendly_name: "Windows should be open?"
        icon_template: >-
          {% if is_state('binary_sensor.windows_should_be_open','on') %}
            mdi:window-open
          {% else %}
            mdi:window-closed
          {% endif %}
        value_template: >-
          {% set forecast_high = states('sensor.pirateweather_daytime_high_temperature_0d')|float %}
          {% set forecast_tomorrow = states('sensor.wupws_temp_high_2d') |float %}
          {% set indoor_temp_av = states('sensor.indoor_temp_average')|float %}
          {% set out_temp_derv = states('sensor.outdoor_temperature_24h_average_derivative')|float %}
          {% set outside_temp = states('sensor.outdoor_temp_average')|float %}
          {% set inside_temp = states('sensor.easyweatherpro_v5_0_9_indoor_temperature')|float %}
          {% set def_summer = indoor_temp_av>72.5 or forecast_high>80 %}
          {% set prob_summer = indoor_temp_av>69.5 and indoor_temp_av<72.5 and (out_temp_derv>0.50 or forecast_high>75) and forecast_tomorrow>70 %}
          {% set poss_summer = indoor_temp_av>66.5 and indoor_temp_av<69.5 and (out_temp_derv>2 or forecast_high>77) and forecast_tomorrow>70 %}
          {% set summer = def_summer or prob_summer or poss_summer %}
          {% set def_winter = indoor_temp_av<66.5 or forecast_high<65 %}
          {% set prob_winter = indoor_temp_av>66.5 and indoor_temp_av<69.5 and (out_temp_derv+1<0 or forecast_high<72) and forecast_tomorrow<79 %}
          {% set poss_winter = indoor_temp_av>69.5 and indoor_temp_av<72.5 and (out_temp_derv+3<0 or forecast_high<70) and forecast_tomorrow<79 %}
          {% set winter = def_winter or prob_winter or poss_winter %}
          {% set dew = states('sensor.dew_point_average')|float %}
          {% set dew_der = states('sensor.dew_point_derivative')|float %}
          {% set dew_low = dew < 62 and inside_temp > dew + 4 %}
          {% set dew_fall = dew < 65.5 and dew_der + 0.25 < 0 and inside_temp > dew + 4 %}
          {% set dew_ideal = dew_low or dew_fall %}
          {% set warmer_outside = outside_temp > inside_temp %}
          {% set warmer_inside = outside_temp < inside_temp %}
          {% set heat_house = warmer_outside and winter %}
          {% set cool_house = warmer_inside and summer %}
          {% set open_in_winter = heat_house and dew_ideal %}
          {% set open_in_summer = cool_house and dew_ideal %}
          {{ open_in_winter or open_in_summer }}
        availability_template: >-
          {% from 'availability_template.jinja' import avail %}
          {{- avail(['sensor.pirateweather_daytime_high_temperature_0d','sensor.wupws_temp_high_2d']) | bool -}}
```

**Comment by SirGoodenough** [comment]
I think it was the lower cast...
last minute throwin

**Comment by SirGoodenough** [comment]
Thanks for finding this, @afxefx 
[2023.12.13](https://github.com/SirGoodenough/Availability-Template/releases/tag/2023.12.13) should be available shortly in HACS for update.
If you don't see it, click on it to refresh information and then back to HA and check for updates.  Otherwise in an hour or so I think these things will happen on their schedule.

**Comment by afxefx** [comment]
Seems to have resolved it, thanks for the quick response and appreciate you!
